version: '3.8'

volumes:
  data:
    driver: local
  mysql_data:
    driver: local
  moodledata:
    driver: local

services:
  amb01:
    container_name: moodle-app
    build: .
    ports:
      - "8080:80"
      - "9443:443"
    volumes:
      - moodledata:/var/www/moodledata
    depends_on:
      - database

  database:
    image: mariadb:latest
    container_name: moodle-db
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle_user
      MYSQL_PASSWORD: mymoodlepass
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: moodle-phpmyadmin
    depends_on:
      - database
    ports:
      - "88:80"
    environment:
      PMA_ARBITRARY: 1
